sudo: required
services:
  - docker

before_install:
  - docker build -t docker-frontend -f Dockerfile.dev .

script:
  - docker run docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerFrontend"
  env: "dockerfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-828961278928"
  bucket_path: "dockerFrontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"